### ISSUE TITLE
Web build support

### ISSUE THREAD

**Issue by Nathan-Franck** [godot-zig/godot-zig#37]
I'm working on trying to get a web build, to see if godot-zig is a good alternative to just publishing my zig game directly to wasm. Currently this is my change to the build.zig

```diff
-    const lib = b.addSharedLibrary(.{
-        .name = "example",
+    const lib = b.addExecutable(.{
+        .name = "libexample",
         .root_source_file = b.path("src/Entry.zig"),
         .target = target,
         .optimize = optimize,
     });
+    lib.entry = .disabled;
+    lib.rdynamic = true;
```

Here's the error I'm getting from firefox and chromium

```
Uncaught (in promise) Error: need the dylink section to be first
    at failIf (index.js:9:9914)
    at getDylinkMetadata (index.js:9:10461)
    at loadWebAssemblyModule (index.js:9:18010)
    at index.js:9:24340
```

I'm assuming I have to do something with emscripten to get this working, thought I'd share anyway :) Thanks!

**Comment by Nathan-Franck** [comment]
Probably related issue - https://github.com/ziglang/zig/issues/18825
